### ISSUE TITLE
Cannot start with two dash

### ISSUE THREAD

**Issue by hiloki** [1000ch/grd#1]
It would be better to change "one dash" modifiers.
*BONUS: Much more lightweight :zap: 

> ...they cannot start with a digit, two hyphens, or a hyphen followed by a digit. ..
> http://www.w3.org/TR/CSS21/syndata.html#characters

**Comment by 1000ch** [comment]
(´；ω；｀)

**Comment by 1000ch** [comment]
1. Safari does not recognize double-dash-started modifier as selector.
    - `--modifier` is not recognized.
    - `\--modifier` is also not recognized.
2. Ordinary prefix style is verbose.
    - `Grid--modifier`
    - `Cell--modifier`
3. How about double-underscore-started modifier?
    - `Grid__modifier` is so **element**ful.
    - Safari also does not recognize it as selector.
4. How about "one dash" modifiers that you recommend?
    - Escaping dash is little boring.
    - But it looks good idea for me, too.

Finally I decided to use "one dash" modifiers.

**Comment by Yimiprod** [comment]
I though it was the syntax from this guidestyle http://rscss.io/
