### ISSUE TITLE
Error installing via npm

### ISSUE THREAD

**Issue by megaghz** [1000ch/grd#11]
I got this error while trying to install this framework via npm >
npm ERR! Refusing to install grd as a dependency of itself

**Comment by 1000ch** [comment]
Are you trying to install `grd` in `grd` folder? If so, you cannot.

**Comment by megaghz** [comment]
so installed in my root as global, and then? how do i use it in other folder?

**Comment by erwstout** [comment]
@megaghz Install at the project level. So lets say you're creating a new project from scratch your flow would look like this:

```sh
$ npm init
$ npm install grd --save
```

`npm init` initializes a `package.json` for your project and `npm install grd --save` installs grd as a dependency of your project, then you can use the grd files found in `node_modules/` from your project.
