### ISSUE TITLE
Decimal percentage has inconsistent behaviour on different browsers

### ISSUE THREAD

**Issue by Jovaage** [1000ch/grd#4]
When using decimals in percentage to represent a fraction, browsers will choose to round differently.
Because of this it would most of the time be better to use `calc`.
For consistency, I recommend doing `calc(100% / 12 * x)` where `x` is the numerator for the grid length fraction.

**Comment by Jovaage** [comment]
I just noticed that this has already been done in src.
However the changes has not been made to dist, and is not what is being demoed.

**Comment by 1000ch** [comment]
Indeed. Using `calc()` might be better. cssnano convert `calc()` to calculated value now, but it can be disabled.

**Comment by 1000ch** [comment]
Fixed in [v1.2.1](https://github.com/1000ch/grd/releases/tag/v1.2.1).
8c68ec679b2e7aeb8624a7f1524ed67153438657
