### ISSUE TITLE
Browser support ?

### ISSUE THREAD

**Issue by l2aelba** [1000ch/grd#7]
For lazy ppl like me :D

http://caniuse.com/#feat=flexbox
http://caniuse.com/#feat=calc
....

**Comment by WanjaStier** [comment]
Yes, why does it say IE11 in the doc?

**Comment by l2aelba** [comment]
@WanjaStier :

> **1000ch committed 5 hours ago**

https://github.com/1000ch/grd/commit/bbcc5bc622275b5594d3abbd078fcba3683ec011

**Comment by julian-goldsmith** [comment]
Flexbox in IE10 is really broken, according to caniuse.com, so IE11 would be the earliest version that can use grd without major changes.

**Comment by 1000ch** [comment]
Mentioned 7e7bb0b0cb980ba2d533fdc61c01de57e8925db7 :ok_hand:

**Comment by Yimiprod** [comment]
i'll leave this here https://github.com/philipwalton/flexbugs
